# Generated by Django 5.1.4 on 2025-04-14 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherprofile_teacherprofileverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
