# Generated by Django 5.1.7 on 2025-04-16 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0004_alter_internship_description_and_more'),
        ('students', '0005_remove_student_address_remove_student_cgpa_and_more'),
        ('teachers', '0003_alter_teacherprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='managements.management')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignment', to='students.student')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='teachers.teacher')),
            ],
        ),
    ]
