# Generated by Django 5.1.7 on 2025-04-16 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_mentorassignment'),
        ('teachers', '0003_alter_teacherprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorassignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_assignments', to='students.student'),
        ),
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together={('student', 'teacher')},
        ),
    ]
