# Generated by Django 5.1.7 on 2025-04-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_mentorassignment_student_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mentorassignment',
            unique_together=set(),
        ),
    ]
