# Generated by Django 5.1.7 on 2025-04-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_alter_mentorassignment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='comments',
            field=models.TextField(blank=True, help_text='Management feedback or notes about the application', null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
