# Generated by Django 5.1.7 on 2025-04-13 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='management',
            options={},
        ),
        migrations.AlterModelManagers(
            name='management',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='management',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='management',
            name='email',
        ),
        migrations.RemoveField(
            model_name='management',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='management',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='management',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='management',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='management',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='management',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='management',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='management',
            name='password',
        ),
        migrations.RemoveField(
            model_name='management',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='management',
            name='username',
        ),
        migrations.AddField(
            model_name='management',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='management',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='management_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
