# Generated by Django 5.1.7 on 2025-04-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managements', '0002_alter_management_options_alter_management_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internships', to='managements.management')),
            ],
        ),
        migrations.CreateModel(
            name='InternshipDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirements', models.TextField()),
                ('responsibilities', models.TextField()),
                ('benefits', models.TextField()),
                ('stipend', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(max_length=100)),
                ('skills_required', models.TextField()),
                ('internship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='managements.internship')),
            ],
        ),
    ]
